# Generated by Django 5.1 on 2024-08-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP адрес')),
                ('user', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя пользователя')),
                ('http_method', models.CharField(blank=True, default='', max_length=10, verbose_name='HTTP метод')),
                ('request_uri', models.TextField(blank=True, default='', verbose_name='URI запроса')),
                ('response_code', models.PositiveSmallIntegerField(null=True, verbose_name='Код ответа')),
                ('response_size', models.IntegerField(null=True, verbose_name='Размер ответа')),
            ],
        ),
    ]
