# Generated by Django 5.1 on 2024-08-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-date'], 'verbose_name': 'Лог запись', 'verbose_name_plural': 'Лог записи'},
        ),
    ]
