# Generated by Django 6.1 on 2026-08-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0002_alter_logentry_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="date",
            field=models.DateTimeField(db_index=True, null=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="http_method",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10, verbose_name="HTTP метод"
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="ip_address",
            field=models.GenericIPAddressField(db_index=True, null=True, verbose_name="IP адрес"),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="response_code",
            field=models.PositiveSmallIntegerField(
                db_index=True, null=True, verbose_name="Код ответа"
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="response_size",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Размер ответа"),
        ),
    ]
